[versions] #------------------------------------------------------------------------------------------------------------

kotlin          = "2.4.10"
kotlin-compiler = "2.4"

android-gradle-plugin = "9.3.1"

android-sdk-compile = "37"  # Android 17, see https://apilevels.com/
android-build-tools = "37.0.0"

android-jvm-target = "1.8" # Java 8 (API 24+), can be Java 11 for API 29+, Java 17 for API 33+

androidx-core       = "1.19.0"
androidx-annotation = "1.10.0"
androidx-activity   = "1.13.0"
androidx-lifecycle  = "2.11.0"
compose-bom         = "2026.06.01"

[plugins] #-------------------------------------------------------------------------------------------------------------

kotlin-jvm           = { id = "org.jetbrains.kotlin.jvm",                 version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform",       version.ref = "kotlin" }
kotlin-android       = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle-plugin" }
kotlin-compose       = { id = "org.jetbrains.kotlin.plugin.compose",      version.ref = "kotlin" }

android-library      = { id = "com.android.library",     version.ref = "android-gradle-plugin" }
android-application  = { id = "com.android.application", version.ref = "android-gradle-plugin" }

[libraries] #-----------------------------------------------------------------------------------------------------------

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

androidx-core       = { module = "androidx.core:core-ktx",                   version.ref = "androidx-core" }
androidx-activity   = { module = "androidx.activity:activity-compose",       version.ref = "androidx-activity" }
androidx-annotation = { module = "androidx.annotation:annotation",           version.ref = "androidx-annotation" }
androidx-lifecycle  = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }

compose-bom         = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui          = { module = "androidx.compose.ui:ui" }
compose-material3   = { module = "androidx.compose.material3:material3" }