name: KMP library publishing

on:
  push:
    branches:
      - kmp
      - kmp-bootstrap-nodes
#    branches: [kmp, master]
#  pull_request:
#    branches: [main, master]
  release:
    types: [created]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./kmp

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2 # https://github.com/actions/checkout

      - name: Set up JDK 21
        uses: actions/setup-java@v5.6.0 # https://github.com/actions/setup-java
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
        
      - name: Publish to GitHub Packages
        run: |
          cd kmp
          chmod +x gradlew
          SHORT_SHA="${GITHUB_SHA:0:7}"
          ./gradlew publishAllPublicationsToGitHubPackagesRepository -Pversion="$SHORT_SHA"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
